export const ApiUrl = {
  getOTP: "/get-otp-api/",
  signUp: "/signup/",
  verOTP: "/verify-otp/",
  pref: "/updatepreference/",
  matched: "/get-matched-preferences/",
  edit: "/updateprofile/",
  f_q: "/faq-api/",
  blog: "/get-blog/",
  search: "/search-profiles/",
  visit: "/visit-profile/",
  plan: "/all-plan-api/",
  buy: "/buy-plan-api/",
  verify_payment: "/verify-payment-api/",
  ver_pro: "/profile-verification-api/",
  sendRequest: "/send-chat-request/",
  getRequest: "/get-received-chat-requests/",
  medical: "/department-management-api/",
};
